// Run against `pnpm dev`: PLAYWRIGHT_MODULE may point to an existing Playwright installation.
// All API requests are intercepted; this test never creates a real discussion or runs a model.
import { createRequire } from "node:module";
import assert from "node:assert/strict";
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || "chrome" });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const people = Array.from({ length: 15 }, (_, i) => ({ id: `p${i}`, name: ["张一鸣", "马云", "雷军"][i] ?? `专家${i}`, perspectiveType: "business" }));
  const messages = ["你好", "你好，很高兴和你讨论。", "先看需求", "可以，先验证目标用户和付费意愿。", "再看成本", "按实际使用量核算即可。"].map((content, i) => ({ id: `m${i}`, sender: i % 2 ? "张一鸣" : "我", role: i % 2 ? "persona" : "user", content, turn: i, createdAt: new Date().toISOString() }));
  const discussion = { id: "ux-fixture", brief: "讨论界面交互验证", status: "done", rounds: 5, personas: people.slice(0, 3), messages };
  let writes = 0;
  await page.route("**/api/**", async (route) => {
    if (route.request().method() !== "GET") writes++;
    const path = new URL(route.request().url()).pathname;
    if (path.endsWith("/stream")) return route.fulfill({ contentType: "text/event-stream", body: ": connected\n\n" });
    const data = path === "/api/v1/discussions/ux-fixture" ? discussion : { items: path === "/api/v1/personas" ? people : path === "/api/v1/recipes" ? [{ id: "r1", name: "市场分析", stepCount: 3 }] : [] };
    await route.fulfill({ json: { code: 0, data } });
  });
  await page.goto("http://localhost:3001/");
  const input = page.getByRole("textbox", { name: "商业想法" });
  await input.fill("测试想法 @");
  const selected = page.getByRole("option", { selected: true });
  await selected.waitFor();
  assert.match(await selected.innerText(), /张一鸣/);
  await input.press("ArrowDown");
  assert.match(await selected.innerText(), /马云/);
  await input.press("ArrowUp");
  assert.match(await selected.innerText(), /张一鸣/);
  await input.press("ArrowUp");
  assert.match(await selected.innerText(), /市场分析/);
  assert(await selected.evaluate((el) => { const parent = el.parentElement.getBoundingClientRect(); const rect = el.getBoundingClientRect(); return rect.top >= parent.top && rect.bottom <= parent.bottom; }));
  await input.press("ArrowDown");
  await input.press("ArrowDown");
  await input.press("Enter");
  assert.equal(await input.inputValue(), "测试想法 @马云 ");
  assert.equal(writes, 0, "selecting a mention must not submit");
  await input.fill("@");
  await input.press("Escape");
  assert.equal(await page.getByRole("listbox").count(), 0);
  await input.fill("@不存在的人物");
  await input.press("Enter");
  assert.equal(writes, 0);
  await input.fill("@");
  await input.dispatchEvent("keydown", { key: "Enter", code: "Enter", isComposing: true });
  assert.equal(await input.inputValue(), "@");
  await input.fill("@张");
  await page.getByRole("option").first().click();
  assert.equal(await input.inputValue(), "@张一鸣 ");
  await page.getByRole("button", { name: "人格视角" }).click();
  await page.getByRole("button", { name: /雷军/ }).click();
  await page.waitForURL("**/personas/p2");
  assert.equal(new URL(page.url()).pathname, "/personas/p2");
  await page.goto("http://localhost:3001/");
  const refreshedInput = page.getByRole("textbox", { name: "商业想法" });
  await refreshedInput.fill("@");
  const color = await page.getByRole("option").first().locator('[aria-label="张一鸣"]').evaluate((el) => getComputedStyle(el).color);
  assert.equal(color, "rgb(255, 255, 255)");
  await page.goto("http://localhost:3001/discussions?id=ux-fixture");
  const chat = page.getByRole("textbox", { name: "讨论消息" });
  await chat.waitFor();
  await chat.fill("@");
  await chat.press("ArrowDown");
  await chat.press("Enter");
  assert.equal(await chat.inputValue(), "@马云 ");
  assert.equal(writes, 0);
  await chat.fill("");
  const smallHeight = (await chat.boundingBox()).height;
  await chat.fill("第一行\n第二行\n第三行\n第四行\n第五行");
  await page.waitForFunction(() => document.querySelector('textarea[aria-label="讨论消息"]').clientHeight > 80);
  assert((await chat.boundingBox()).height > smallHeight);
  await chat.fill("");
  const bubbles = await page.locator("article > div.rounded-lg").evaluateAll((elements) => elements.map((el) => ({ width: el.clientWidth, parent: el.parentElement.clientWidth })));
  assert.equal(bubbles.length, 6);
  assert(bubbles.every((bubble) => bubble.width < bubble.parent * 0.75), "short messages should shrink to content");
  const visibleMessages = await page.locator("article").evaluateAll((elements) => elements.filter((el) => { const r = el.getBoundingClientRect(); return r.top >= 100 && r.bottom < window.innerHeight - 140; }).length);
  assert(visibleMessages >= 4, `only ${visibleMessages} short messages visible`);
  for (const width of [1440, 768, 390]) {
    await page.setViewportSize({ width, height: 900 });
    await chat.fill("长文本".repeat(120));
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `overflow at ${width}`);
    const box = await chat.boundingBox();
    assert(box.y + box.height <= 900, "composer must stay in viewport");
  }
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ passed: true, writes, visibleMessages, bubbles, smallHeight, avatarColor: color, widths: [1440, 768, 390] }));
} finally { await browser.close(); }
