allowBuilds:
  esbuild: false
  "@prisma/engines": true
  prisma: true
  "@prisma/client": true
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
  workerd: false
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  koffi: true
  node-pty: true
  protobufjs: true
