/**
 * Worker 级 Runtime 单例。一个 Worker（Next.js 服务进程）只持有一个 DSH Runtime，
 * 通过 DshRuntimeManager 管理生命周期、Session mutex 与 profile 一致性。
 *
 * 关键：确保使用「项目自己的 @deepseek-ai/dsh CLI」，绝不碰用户桌面的 DSH 环境。
 * 做法：
 *  - dshBin：显式解析到本项目 @deepseek-ai/dsh 包的真实 bin（避免回退到桌面版 Electron）。
 *  - dshHome：指向项目内 data/dsh-home，运行时状态（session/profile/config）只在项目内读写。
 *  - env：显式构建、剔除 NODE_OPTIONS 等（桌面 packaged app 会因 NODE_OPTIONS 报错），并把
 *    BT_DSH_LLM_API_KEY 注入该 env（不写 system prompt / manifest / 日志）。
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import { DshRuntimeManager } from "./manager";
import { buildRuntimeProfile, type ProfileInput } from "./profile";
import { getSetting } from "@/lib/settings/store";
import { decrypt } from "@/lib/settings/encryption";
import { DshCredentialInvalidError } from "@/lib/dsh/errors";
import type { RuntimeProfile } from "./types";

let manager: DshRuntimeManager | null = null;

export interface DshTurnConfig {
  profile: RuntimeProfile;
  apiKey: string;
  cwd: string;
  dshBin?: string;
  dshHome: string;
  patches: string[];
}

/** 解析 `@deepseek-ai/dsh` 包的真实 CLI bin（相对项目，避免解析到桌面版） */
export function resolveDshBin(cwd: string): string | undefined {
  try {
    const req = createRequire(path.join(cwd, "noop.js"));
    const manifestPath = req.resolve("@deepseek-ai/dsh/package.json");
    const pkg = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as { bin?: Record<string, string> };
    const binRel = pkg.bin?.dsh ?? pkg.bin;
    if (typeof binRel === "string") return path.join(path.dirname(manifestPath), binRel);
  } catch {
    /* 回退由 SDK 解析同版本包 bin */
  }
  return undefined;
}

/** 生成 BT 插件 patch（file:// 绝对路径；相对路径在 pnpm 布局的 dsh 运行时下无法装载） */
export function ensurePluginPatch(cwd: string): string {
  const pluginPath = path.join(cwd, "runtime", "dsh-plugin", "index.mjs");
  const url = pathToFileURL(pluginPath).href;
  const patch = `# generated by dsh/singleton.ts — BT plugin mount\n- insert:\n    - id: business-talking\n      name: '${url}'\n`;
  const outDir = path.join(cwd, "data", "dsh");
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, "cordis-bt-plugin.patch.yml");
  fs.writeFileSync(out, patch, "utf8");
  return out;
}

/** 构建最小的 child env（白名单）：只保留系统必要项 + API key，避免 next dev 注入的环境变量干扰 dsh CLI */
function buildChildEnv(): NodeJS.ProcessEnv {
  const ALLOW = new Set([
    "PATH", "Path", "HOME", "USERPROFILE", "TEMP", "TMP", "TMPDIR",
    "SystemRoot", "SYSTEMROOT", "COMSPEC", "PATHEXT", "WINDIR", "ProgramFiles", "ProgramFiles(x86)",
    "LANG", "LC_ALL", "NODE_PATH", "PWD", "INIT_CWD", "APPDATA", "LOCALAPPDATA",
  ]);
  const env = {} as NodeJS.ProcessEnv;
  for (const k of Object.keys(process.env)) {
    if (ALLOW.has(k)) env[k] = process.env[k];
  }
  return env;
}

/** 稳健的项目根：优先 package.json 所在目录，回退 process.cwd() */
export function projectRoot(): string {
  let dir = process.cwd();
  for (let i = 0; i < 6; i++) {
    if (fs.existsSync(path.join(dir, "package.json"))) return dir;
    dir = path.dirname(dir);
  }
  return process.cwd();
}

/** DSH 的所有可写运行时状态都隔离在项目数据目录，不回落到用户全局 ~/.dsh。 */
export function runtimeDshHome(cwd: string): string {
  return path.join(cwd, "data", "dsh-home");
}

/**
 * 读取一次 DSH 回合所需的完整配置，但不启动常驻 Runtime。
 * 独立回合进程必须把 sessionId 和对应 manifest 一起传给 DSH 子进程，
 * 所以这里集中返回与生产 Runtime 相同的 bin/home/patch 配置。
 */
export async function getDshTurnConfig(): Promise<DshTurnConfig> {
  const [provider, baseUrl, keyCipher, defaultModel] = await Promise.all([
    getSetting("llm.provider"),
    getSetting("llm.baseUrl"),
    getSetting("llm.apiKey"),
    getSetting("llm.defaultModel"),
  ]);
  const profile = buildRuntimeProfile({ provider, baseUrl, defaultModel } as ProfileInput);
  const apiKey = keyCipher ? decrypt(keyCipher) : "";
  if (!apiKey) throw new DshCredentialInvalidError();

  const cwd = projectRoot();
  const basePatch = path.join(cwd, "runtime", "dsh", "cordis.patch.yml");
  return {
    profile,
    apiKey,
    cwd,
    dshBin: resolveDshBin(cwd),
    dshHome: runtimeDshHome(cwd),
    patches: [basePatch, ensurePluginPatch(cwd)],
  };
}

/** 全局 Runtime manager（懒创建）。用项目 CLI + 干净 env，不触发桌面 Electron。 */
export function getRuntimeManager(): DshRuntimeManager {
  if (!manager) {
    const cwd = projectRoot();
    const dshHome = runtimeDshHome(cwd);
    fs.mkdirSync(dshHome, { recursive: true });
    const basePatch = path.join(cwd, "runtime", "dsh", "cordis.patch.yml");
    const pluginPatch = ensurePluginPatch(cwd);
    manager = new DshRuntimeManager({
      cwd,
      patches: [basePatch, pluginPatch],
      dshBin: resolveDshBin(cwd),
      dshHome,
      env: buildChildEnv(),
    });
  }
  return manager;
}

/**
 * 从 LLM 设置构建 runtime profile，并拉起 Runtime。
 * apiKey 解密后仅注入 child env（SDK 在 spawn 时读取），不落盘、不进 manifest/日志。
 */
export async function ensureStartedForSettings(): Promise<RuntimeProfile> {
  const config = await getDshTurnConfig();
  const mgr = getRuntimeManager();
  // 把解密后的 key 放进 child env（SDK spawn 时读取）；不写父进程 process.env。
  // deepseek-official 路由经由 DSH 凭据读取，这里同时覆盖常见 env 名以最大化命中。
  if (mgr.childEnv) {
    mgr.childEnv.BT_DSH_LLM_API_KEY = config.apiKey;
    mgr.childEnv.DEEPSEEK_API_KEY = config.apiKey;
    mgr.childEnv.OPENAI_API_KEY = config.apiKey;
    mgr.childEnv.ANTHROPIC_API_KEY = config.apiKey;
  }
  // 诊断：打印实际启动配置（不含 secret）
  console.error("[dsh-startup]", JSON.stringify({ provider: config.profile.provider, dshRoute: config.profile.dshRoute, model: config.profile.model, baseUrl: config.profile.baseUrl, cwd: config.cwd, dshBin: config.dshBin, dshHome: config.dshHome }));
  await mgr.ensureStarted(config.profile);
  return config.profile;
}

/** 关闭并清空 Runtime（Worker shutdown / drain 时调用） */
export async function shutdownRuntime(): Promise<void> {
  if (manager) {
    await manager.close();
    manager = null;
  }
}
